In [31]:
import polars as pl

train_features = pl.scan_parquet(r"C:\Users\artem\PycharmProjects\Data Fusion Contest 2026\Data_Fusion_2026\data\train_main_features.parquet")
train_target = pl.scan_parquet(r"C:\Users\artem\PycharmProjects\Data Fusion Contest 2026\Data_Fusion_2026\data\train_target.parquet")

train_features = train_features.collect()

train_features.head()

shape: (5, 200)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ customer_ ┆ cat_featu ┆ cat_featu ┆ cat_featu ┆ … ┆ num_featu ┆ num_featu ┆ num_featu ┆ num_feat │
│ id        ┆ re_1      ┆ re_2      ┆ re_3      ┆   ┆ re_129    ┆ re_130    ┆ re_131    ┆ ure_132  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i32       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1000001   ┆ 1.0       ┆ 0.0       ┆ 2.0       ┆ … ┆ -0.107666 ┆ -0.418616 ┆ null      ┆ null     │
│ 1000002   ┆ 1.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ -0.170724 ┆ -0.805771 ┆ -0.397803 ┆ -0.37373 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 1000003   ┆ 1.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ -0.170724 ┆ -0.602005 ┆ -0.397803 ┆ -0.37373 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 1000004   ┆ 1.0       ┆ 0.0       ┆ 2.0       ┆ … ┆ null      ┆ -0.724265 ┆ null      ┆ null     │
│ 1000005   ┆ 1.0       ┆ 2.0       ┆ 0.0       ┆ … ┆ -0.107666 ┆ null      ┆ -0.397803 ┆ -0.37373 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [32]:
train_features.schema

Schema([('customer_id', Int32),
        ('cat_feature_1', Float64),
        ('cat_feature_2', Float64),
        ('cat_feature_3', Float64),
        ('cat_feature_4', Float64),
        ('cat_feature_5', Float64),
        ('cat_feature_6', Float64),
        ('cat_feature_7', Float64),
        ('cat_feature_8', Float64),
        ('cat_feature_9', Float64),
        ('cat_feature_10', Float64),
        ('cat_feature_11', Float64),
        ('cat_feature_12', Float64),
        ('cat_feature_13', Float64),
        ('cat_feature_14', Float64),
        ('cat_feature_15', Float64),
        ('cat_feature_16', Float64),
        ('cat_feature_17', Float64),
        ('cat_feature_18', Float64),
        ('cat_feature_19', Float64),
        ('cat_feature_20', Float64),
        ('cat_feature_21', Float64),
        ('cat_feature_22', Float64),
        ('cat_feature_23', Float64),
        ('cat_feature_24', Float64),
        ('cat_feature_25', Float64),
        ('cat_feature_26', Float64),
        ('cat_feature_27', Float64),
        ('cat_feature_28', Float64),
        ('cat_feature_29', Float64),
        ('cat_feature_30', Float64),
        ('cat_feature_31', Float64),
        ('cat_feature_32', Float64),
        ('cat_feature_33', Float64),
        ('cat_feature_34', Float64),
        ('cat_feature_35', Float64),
        ('cat_feature_36', Float64),
        ('cat_feature_37', Float64),
        ('cat_feature_38', Float64),
        ('cat_feature_39', Float64),
        ('cat_feature_40', Float64),
        ('cat_feature_41', Float64),
        ('cat_feature_42', Float64),
        ('cat_feature_43', Float64),
        ('cat_feature_44', Float64),
        ('cat_feature_45', Float64),
        ('cat_feature_46', Float64),
        ('cat_feature_47', Float64),
        ('cat_feature_48', Float64),
        ('cat_feature_49', Float64),
        ('cat_feature_50', Float64),
        ('cat_feature_51', Float64),
        ('cat_feature_52', Float64),
        ('cat_feature_53', Float64),
        ('cat_feature_54', Float64),
        ('cat_feature_55', Float64),
        ('cat_feature_56', Float64),
        ('cat_feature_57', Float64),
        ('cat_feature_58', Float64),
        ('cat_feature_59', Float64),
        ('cat_feature_60', Float64),
        ('cat_feature_61', Float64),
        ('cat_feature_62', Float64),
        ('cat_feature_63', Float64),
        ('cat_feature_64', Float64),
        ('cat_feature_65', Float64),
        ('cat_feature_66', Float64),
        ('cat_feature_67', Float64),
        ('num_feature_1', Float64),
        ('num_feature_2', Float64),
        ('num_feature_3', Float64),
        ('num_feature_4', Float64),
        ('num_feature_5', Float64),
        ('num_feature_6', Float64),
        ('num_feature_7', Float64),
        ('num_feature_8', Float64),
        ('num_feature_9', Float64),
        ('num_feature_10', Float64),
        ('num_feature_11', Float64),
        ('num_feature_12', Float64),
        ('num_feature_13', Float64),
        ('num_feature_14', Float64),
        ('num_feature_15', Float64),
        ('num_feature_16', Float64),
        ('num_feature_17', Float64),
        ('num_feature_18', Float64),
        ('num_feature_19', Float64),
        ('num_feature_20', Float64),
        ('num_feature_21', Float64),
        ('num_feature_22', Float64),
        ('num_feature_23', Float64),
        ('num_feature_24', Float64),
        ('num_feature_25', Float64),
        ('num_feature_26', Float64),
        ('num_feature_27', Float64),
        ('num_feature_28', Float64),
        ('num_feature_29', Float64),
        ('num_feature_30', Float64),
        ('num_feature_31', Float64),
        ('num_feature_32', Float64),
        ('num_feature_33', Float64),
        ('num_feature_34', Float64),
        ('num_feature_35', Float64),
        ('num_feature_36', Float64),
        ('num_feature_37', Float64),
        ('num_feature_38', Float64),
        ('num_feature_39', Float64),
        ('num_feature_40', Float64),
        ('num_feature_41', Float64),
        ('num_feature_42', Float64),
        ('num_feature_43', Float64),
        ('num_feature_44', Float64),
        ('num_feature_45', Float64),
        ('num_feature_46', Float64),
        ('num_feature_47', Float64),
        ('num_feature_48', Float64),
        ('num_feature_49', Float64),
        ('num_feature_50', Float64),
        ('num_feature_51', Float64),
        ('num_feature_52', Float64),
        ('num_feature_53', Float64),
        ('num_feature_54', Float64),
        ('num_feature_55', Float64),
        ('num_feature_56', Float64),
        ('num_feature_57', Float64),
        ('num_feature_58', Float64),
        ('num_feature_59', Float64),
        ('num_feature_60', Float64),
        ('num_feature_61', Float64),
        ('num_feature_62', Float64),
        ('num_feature_63', Float64),
        ('num_feature_64', Float64),
        ('num_feature_65', Float64),
        ('num_feature_66', Float64),
        ('num_feature_67', Float64),
        ('num_feature_68', Float64),
        ('num_feature_69', Float64),
        ('num_feature_70', Float64),
        ('num_feature_71', Float64),
        ('num_feature_72', Float64),
        ('num_feature_73', Float64),
        ('num_feature_74', Float64),
        ('num_feature_75', Float64),
        ('num_feature_76', Float64),
        ('num_feature_77', Float64),
        ('num_feature_78', Float64),
        ('num_feature_79', Float64),
        ('num_feature_80', Float64),
        ('num_feature_81', Float64),
        ('num_feature_82', Float64),
        ('num_feature_83', Float64),
        ('num_feature_84', Float64),
        ('num_feature_85', Float64),
        ('num_feature_86', Float64),
        ('num_feature_87', Float64),
        ('num_feature_88', Float64),
        ('num_feature_89', Float64),
        ('num_feature_90', Float64),
        ('num_feature_91', Float64),
        ('num_feature_92', Float64),
        ('num_feature_93', Float64),
        ('num_feature_94', Float64),
        ('num_feature_95', Float64),
        ('num_feature_96', Float64),
        ('num_feature_97', Float64),
        ('num_feature_98', Float64),
        ('num_feature_99', Float64),
        ('num_feature_100', Float64),
        ('num_feature_101', Float64),
        ('num_feature_102', Float64),
        ('num_feature_103', Float64),
        ('num_feature_104', Float64),
        ('num_feature_105', Float64),
        ('num_feature_106', Float64),
        ('num_feature_107', Float64),
        ('num_feature_108', Float64),
        ('num_feature_109', Float64),
        ('num_feature_110', Float64),
        ('num_feature_111', Float64),
        ('num_feature_112', Float64),
        ('num_feature_113', Float64),
        ('num_feature_114', Float64),
        ('num_feature_115', Float64),
        ('num_feature_116', Float64),
        ('num_feature_117', Float64),
        ('num_feature_118', Float64),
        ('num_feature_119', Float64),
        ('num_feature_120', Float64),
        ('num_feature_121', Float64),
        ('num_feature_122', Float64),
        ('num_feature_123', Float64),
        ('num_feature_124', Float64),
        ('num_feature_125', Float64),
        ('num_feature_126', Float64),
        ('num_feature_127', Float64),
        ('num_feature_128', Float64),
        ('num_feature_129', Float64),
        ('num_feature_130', Float64),
        ('num_feature_131', Float64),
        ('num_feature_132', Float64)])

In [33]:
train_features.null_count()

shape: (1, 200)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ customer_ ┆ cat_featu ┆ cat_featu ┆ cat_featu ┆ … ┆ num_featu ┆ num_featu ┆ num_featu ┆ num_feat │
│ id        ┆ re_1      ┆ re_2      ┆ re_3      ┆   ┆ re_129    ┆ re_130    ┆ re_131    ┆ ure_132  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 252042    ┆ 310105    ┆ 425799    ┆ 425799   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [34]:
train_features.describe()

shape: (9, 201)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ customer_ ┆ cat_featu ┆ cat_featu ┆ … ┆ num_featu ┆ num_featu ┆ num_featu ┆ num_feat │
│ ---       ┆ id        ┆ re_1      ┆ re_2      ┆   ┆ re_129    ┆ re_130    ┆ re_131    ┆ ure_132  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 750000.0  ┆ 750000.0  ┆ 750000.0  ┆ … ┆ 497958.0  ┆ 439895.0  ┆ 324201.0  ┆ 324201.0 │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 252042.0  ┆ 310105.0  ┆ 425799.0  ┆ 425799.0 │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 1375000.5 ┆ 0.720465  ┆ 0.398201  ┆ … ┆ 0.000495  ┆ 0.000818  ┆ 0.000709  ┆ 0.000233 │
│ std       ┆ 216506.49 ┆ 0.448771  ┆ 0.745856  ┆ … ┆ 1.06391   ┆ 1.014561  ┆ 1.000476  ┆ 0.994874 │
│           ┆ 5284      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 1.000001e ┆ 0.0       ┆ 0.0       ┆ … ┆ -0.170724 ┆ -0.805771 ┆ -0.397803 ┆ -0.37373 │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 25%       ┆ 1.187501e ┆ 0.0       ┆ 0.0       ┆ … ┆ -0.170724 ┆ -0.683511 ┆ -0.397803 ┆ -0.37373 │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 50%       ┆ 1.375001e ┆ 1.0       ┆ 0.0       ┆ … ┆ -0.107666 ┆ -0.316734 ┆ -0.397803 ┆ -0.37373 │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 75%       ┆ 1.5625e6  ┆ 1.0       ┆ 0.0       ┆ … ┆ 0.018451  ┆ 0.335315  ┆ -0.397803 ┆ -0.37373 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ max       ┆ 1.75e6    ┆ 1.0       ┆ 2.0       ┆ … ┆ 451.83256 ┆ 101.36217 ┆ 24.022368 ┆ 72.66028 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆ 8        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [35]:
train_features.columns

['customer_id',
 'cat_feature_1',
 'cat_feature_2',
 'cat_feature_3',
 'cat_feature_4',
 'cat_feature_5',
 'cat_feature_6',
 'cat_feature_7',
 'cat_feature_8',
 'cat_feature_9',
 'cat_feature_10',
 'cat_feature_11',
 'cat_feature_12',
 'cat_feature_13',
 'cat_feature_14',
 'cat_feature_15',
 'cat_feature_16',
 'cat_feature_17',
 'cat_feature_18',
 'cat_feature_19',
 'cat_feature_20',
 'cat_feature_21',
 'cat_feature_22',
 'cat_feature_23',
 'cat_feature_24',
 'cat_feature_25',
 'cat_feature_26',
 'cat_feature_27',
 'cat_feature_28',
 'cat_feature_29',
 'cat_feature_30',
 'cat_feature_31',
 'cat_feature_32',
 'cat_feature_33',
 'cat_feature_34',
 'cat_feature_35',
 'cat_feature_36',
 'cat_feature_37',
 'cat_feature_38',
 'cat_feature_39',
 'cat_feature_40',
 'cat_feature_41',
 'cat_feature_42',
 'cat_feature_43',
 'cat_feature_44',
 'cat_feature_45',
 'cat_feature_46',
 'cat_feature_47',
 'cat_feature_48',
 'cat_feature_49',
 'cat_feature_50',
 'cat_feature_51',
 'cat_feature_52',
 'cat_feature_53',
 'cat_feature_54',
 'cat_feature_55',
 'cat_feature_56',
 'cat_feature_57',
 'cat_feature_58',
 'cat_feature_59',
 'cat_feature_60',
 'cat_feature_61',
 'cat_feature_62',
 'cat_feature_63',
 'cat_feature_64',
 'cat_feature_65',
 'cat_feature_66',
 'cat_feature_67',
 'num_feature_1',
 'num_feature_2',
 'num_feature_3',
 'num_feature_4',
 'num_feature_5',
 'num_feature_6',
 'num_feature_7',
 'num_feature_8',
 'num_feature_9',
 'num_feature_10',
 'num_feature_11',
 'num_feature_12',
 'num_feature_13',
 'num_feature_14',
 'num_feature_15',
 'num_feature_16',
 'num_feature_17',
 'num_feature_18',
 'num_feature_19',
 'num_feature_20',
 'num_feature_21',
 'num_feature_22',
 'num_feature_23',
 'num_feature_24',
 'num_feature_25',
 'num_feature_26',
 'num_feature_27',
 'num_feature_28',
 'num_feature_29',
 'num_feature_30',
 'num_feature_31',
 'num_feature_32',
 'num_feature_33',
 'num_feature_34',
 'num_feature_35',
 'num_feature_36',
 'num_feature_37',
 'num_feature_38',
 'num_feature_39',
 'num_feature_40',
 'num_feature_41',
 'num_feature_42',
 'num_feature_43',
 'num_feature_44',
 'num_feature_45',
 'num_feature_46',
 'num_feature_47',
 'num_feature_48',
 'num_feature_49',
 'num_feature_50',
 'num_feature_51',
 'num_feature_52',
 'num_feature_53',
 'num_feature_54',
 'num_feature_55',
 'num_feature_56',
 'num_feature_57',
 'num_feature_58',
 'num_feature_59',
 'num_feature_60',
 'num_feature_61',
 'num_feature_62',
 'num_feature_63',
 'num_feature_64',
 'num_feature_65',
 'num_feature_66',
 'num_feature_67',
 'num_feature_68',
 'num_feature_69',
 'num_feature_70',
 'num_feature_71',
 'num_feature_72',
 'num_feature_73',
 'num_feature_74',
 'num_feature_75',
 'num_feature_76',
 'num_feature_77',
 'num_feature_78',
 'num_feature_79',
 'num_feature_80',
 'num_feature_81',
 'num_feature_82',
 'num_feature_83',
 'num_feature_84',
 'num_feature_85',
 'num_feature_86',
 'num_feature_87',
 'num_feature_88',
 'num_feature_89',
 'num_feature_90',
 'num_feature_91',
 'num_feature_92',
 'num_feature_93',
 'num_feature_94',
 'num_feature_95',
 'num_feature_96',
 'num_feature_97',
 'num_feature_98',
 'num_feature_99',
 'num_feature_100',
 'num_feature_101',
 'num_feature_102',
 'num_feature_103',
 'num_feature_104',
 'num_feature_105',
 'num_feature_106',
 'num_feature_107',
 'num_feature_108',
 'num_feature_109',
 'num_feature_110',
 'num_feature_111',
 'num_feature_112',
 'num_feature_113',
 'num_feature_114',
 'num_feature_115',
 'num_feature_116',
 'num_feature_117',
 'num_feature_118',
 'num_feature_119',
 'num_feature_120',
 'num_feature_121',
 'num_feature_122',
 'num_feature_123',
 'num_feature_124',
 'num_feature_125',
 'num_feature_126',
 'num_feature_127',
 'num_feature_128',
 'num_feature_129',
 'num_feature_130',
 'num_feature_131',
 'num_feature_132']

In [37]:
train_target_df = train_target.collect()

train_target_df.head()

shape: (5, 42)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ customer_ ┆ target_1_ ┆ target_1_ ┆ target_1_ ┆ … ┆ target_9_ ┆ target_9_ ┆ target_9_ ┆ target_1 │
│ id        ┆ 1         ┆ 2         ┆ 3         ┆   ┆ 6         ┆ 7         ┆ 8         ┆ 0_1      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i32       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1000001   ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 1.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 1000002   ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 1000003   ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1000004   ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 1.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 1000005   ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘